name: chromatic
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rxlib-react
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
        working-directory: packages/rxlib-react
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/rxlib-react
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}